---
# Deploy configurado para ADF Soluções Digital
# Última atualização: 18/01/2026
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - cd $DEPLOYPATH
    - npm install --production=false
    - npm run build
    - /bin/rm -rf assets blog icons images index.html manifest.json robots.txt sitemap.xml *.svg 2>/dev/null || true
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp dist/.htaccess $DEPLOYPATH/.htaccess 2>/dev/null || /bin/cp .htaccess $DEPLOYPATH/.htaccess 2>/dev/null || echo ".htaccess não encontrado"
    - /bin/rm -rf node_modules dist src server public .git .gitignore package.json package-lock.json tsconfig.json tsconfig.app.json tsconfig.node.json vite.config.ts vite.config.js eslint.config.js README.md .cpanel.yml DEPLOY.md tsconfig.tsbuildinfo tsconfig.node.tsbuildinfo 2>/dev/null || true
    - /bin/chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || echo "Ajustando permissões"
    - /bin/chmod 755 $DEPLOYPATH 2>/dev/null || echo "Ajustando permissões do diretório"
    - echo "Deploy concluído com sucesso!"

