---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adfsolucoes/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production=false
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/rm -rf node_modules dist src server public .git .gitignore package.json package-lock.json tsconfig.json tsconfig.app.json tsconfig.node.json vite.config.ts vite.config.js eslint.config.js README.md .cpanel.yml

