---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adfsolucoes/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production=false
    - npm run build
    - /bin/rm -rf node_modules

