---
# Deploy configurado para ADF Soluções Digital
# Última atualização: 18/01/2026 21:10
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /bin/cp -R * $DEPLOYPATH/ 2>/dev/null || /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production=false
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH/
    - /bin/cp dist/.htaccess $DEPLOYPATH/.htaccess 2>/dev/null || /bin/cp .htaccess $DEPLOYPATH/.htaccess 2>/dev/null || echo ".htaccess não encontrado"
    - /bin/rm -rf node_modules dist src server public .git .gitignore package.json package-lock.json tsconfig.json tsconfig.app.json tsconfig.node.json vite.config.ts vite.config.js eslint.config.js README.md .cpanel.yml DEPLOY.md
    - /bin/chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || echo "Ajustando permissões"
    - /bin/chmod 755 $DEPLOYPATH 2>/dev/null || echo "Ajustando permissões do diretório"
    - echo "✅ Deploy concluído com sucesso! - $(date)"

