---
deployment:
  tasks:
    - export REPOPATH=$HOME/repositories/adf-solucoes-digital-v2
    - export DEPLOYPATH=$HOME/public_html
    - cd $REPOPATH
    - npm install --production=false
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/assets $DEPLOYPATH/blog $DEPLOYPATH/icons $DEPLOYPATH/images $DEPLOYPATH/index.html $DEPLOYPATH/manifest.json $DEPLOYPATH/robots.txt $DEPLOYPATH/sitemap.xml 2>/dev/null || true
    - /bin/cp -R $REPOPATH/dist/* $DEPLOYPATH/
    - /bin/cp $REPOPATH/dist/.htaccess $DEPLOYPATH/.htaccess 2>/dev/null || /bin/cp $REPOPATH/.htaccess $DEPLOYPATH/.htaccess 2>/dev/null || true
    - /bin/chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || true
    - /bin/chmod 755 $DEPLOYPATH 2>/dev/null || true
